FROM centos:8
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN yum -y install git epel-release && yum -y install python3-pip && yum clean all && rm -rf /var/cache/yum
RUN pip install --upgrade pip setuptools && pip install git+git://github.com/kubernetes-incubator/client-python.git
