apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: guitars.kool.karmalabs.local
spec:
  group: kool.karmalabs.local
  versions: 
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                brand:
                  type: string
                review:
                  type: boolean
  scope: Namespaced
  names:
    plural: guitars
    singular: guitar
    kind: Guitar
    shortNames:
     - guit
